### PR TITLE
Moving to json gameplans instead of csv

### PR DESCRIPTION
**Pull request by linus-jansson**
Changed to json to make it easier to create gameplans and debug gameplans.

Also created another class to represent the settings and the gameclass which the bot will use

### CODE REVIEW

**Comment by linus-jansson** [comment]
Should be tested with #16 to see if it fixes the issue

**Comment by linus-jansson** [comment]
Update: Tested with 4 consecutive matches without fail

**Comment by linus-jansson** [comment]
from stats file
``` json
{
    "wins": 4,
    "loses": 0,
    "winrate": "100.0%",
    "average_matchtime": "14.066 min",
    "total_time": 3375.839364051819,
    "average_matchtime_seconds": 843.9598410129547
}
```

**Comment by jason00-r** [comment]
thanks for your work on this

**Pull request merged**
