### PR TITLE
Alt+Tabbing or Pausing won't clear the coords

### PR DESCRIPTION
**Pull request by TheFutureKnight**

### CODE REVIEW

**Comment by linus-jansson** [comment]
Would it be possible for your PRs to branch of the rewrite branch?

**Comment by TheFutureKnight** [comment]
Sure, want me to pr both or just rewrite?

**Comment by linus-jansson** [comment]
I changed the base branch, if you want to you can fix the merge conflict. Otherwise I will fix it when I get to it

**Comment by TheFutureKnight** [comment]
Alright I'll get to it asap

**Comment by TheFutureKnight** [comment]
Actually the file this PR intended to fix is on main branch and probably won't move over to rewrite (Due to it being deleted), the last commit is already inside another PR anyways, want me to re-open the PR for just the main branch changes?

**Comment by linus-jansson** [comment]
Yeah sure

**Pull request closed without merging**
